del Backend.exe
copy "C:\Data\Peernet\Cmd\Cmd.exe" Backend.exe
signtool sign /a /fd SHA256 Backend.exe

del "Peernet.Browser.WPF\Application.dll"
del "Peernet.Browser.WPF\Infrastructure.dll"
del "Peernet.Browser.WPF\Microsoft.Extensions.DependencyInjection.Abstractions.dll"
del "Peernet.Browser.WPF\Microsoft.Extensions.Logging.Abstractions.dll"
del "Peernet.Browser.WPF\Microsoft.Extensions.Logging.dll"
del "Peernet.Browser.WPF\Microsoft.Extensions.Options.dll"
del "Peernet.Browser.WPF\Microsoft.Extensions.Primitives.dll"
del "Peernet.Browser.WPF\Models.dll"
del "Peernet.Browser.WPF\MvvmCross.dll"
del "Peernet.Browser.WPF\MvvmCross.Platforms.Wpf.dll"
del "Peernet.Browser.WPF\MvvmCross.Plugin.Control.dll"
del "Peernet.Browser.WPF\MvvmCross.Plugin.Control.Platforms.Wpf.dll"
del "Peernet.Browser.WPF\Newtonsoft.Json.dll"
del "Peernet.Browser.WPF\Peernet Browser.deps.json"
del "Peernet.Browser.WPF\Peernet Browser.dll"
del "Peernet.Browser.WPF\Peernet Browser.exe"
del "Peernet.Browser.WPF\Peernet Browser.runtimeconfig.json"
del "Peernet.Browser.WPF\Serilog.dll"
del "Peernet.Browser.WPF\Serilog.Extensions.Logging.dll"
del "Peernet.Browser.WPF\Serilog.Sinks.Trace.dll"
del "Peernet.Browser.WPF\System.Drawing.Common.dll"

copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Application.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Infrastructure.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Microsoft.Extensions.DependencyInjection.Abstractions.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Microsoft.Extensions.Logging.Abstractions.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Microsoft.Extensions.Logging.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Microsoft.Extensions.Options.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Microsoft.Extensions.Primitives.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Models.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\MvvmCross.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\MvvmCross.Platforms.Wpf.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\MvvmCross.Plugin.Control.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\MvvmCross.Plugin.Control.Platforms.Wpf.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Newtonsoft.Json.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Peernet Browser.deps.json" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Peernet Browser.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Peernet Browser.exe" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Peernet Browser.runtimeconfig.json" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Serilog.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Serilog.Extensions.Logging.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\Serilog.Sinks.Trace.dll" "Peernet.Browser.WPF\"
copy "C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net5.0-windows\win-x64\publish\System.Drawing.Common.dll" "Peernet.Browser.WPF\"

signtool sign /a /fd SHA256 "Peernet.Browser.WPF\Peernet Browser.exe"
signtool sign /a /fd SHA256 "Peernet.Browser.WPF\Application.dll"
signtool sign /a /fd SHA256 "Peernet.Browser.WPF\Infrastructure.dll"
signtool sign /a /fd SHA256 "Peernet.Browser.WPF\Models.dll"
signtool sign /a /fd SHA256 "Peernet.Browser.WPF\MvvmCross.Plugin.Control.dll"
signtool sign /a /fd SHA256 "Peernet.Browser.WPF\MvvmCross.Plugin.Control.Platforms.Wpf.dll"
signtool sign /a /fd SHA256 "Peernet.Browser.WPF\Peernet Browser.dll"
signtool sign /a /fd SHA256 "Peernet.Browser.WPF\Serilog.dll"
signtool sign /a /fd SHA256 "Peernet.Browser.WPF\Serilog.Extensions.Logging.dll"
signtool sign /a /fd SHA256 "Peernet.Browser.WPF\Serilog.Sinks.Trace.dll"

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv" "Peernet.Browser.Setup\Peernet.Browser.Setup.vdproj" /build "Release|Any CPU"
"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86\msiinfo" "Peernet.Browser.Setup\Release\Peernet.Browser.Setup.msi" -w 10

signtool sign /a /fd SHA256 "Peernet.Browser.Setup\Release\Peernet.Browser.Setup.msi"
